
services:
  postgres:
    container_name: postgres_containerC1221165
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderDB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_containerC1221165
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@just.edu.so
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
